title: The GreatGita Granth
description: The Great Gita Granth, a living Life Science, simplified for one and all in a easy and comfortably accessible language, highly practical, human behaviour, Be one and be for all as create the Creator, know yourself from ithin yourself
theme: minima
